{{- if .Values.postgresql.secret.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.postgresql.secret.name | default (include "postgresql-verkstedt.fullname" .) }}
  labels:
    {{- include "postgresql-verkstedt.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.postgresql.secret.data }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end }}
{{- end }}
