kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "monitoring-verkstedt.fullname" . }}-prometheus-config
  labels:
    {{- include "monitoring-verkstedt.labels" . | nindent 4 }}
data:
  prometheus.yml: |
{{ .Values.conf.prometheus | indent 4 }}
