kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ include "monitoring-verkstedt.fullname" . }}-node-exporter
  labels:
    {{- include "monitoring-verkstedt.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "monitoring-verkstedt.name" . }}
      app.kubernetes.io/component: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "monitoring-verkstedt.name" . }}
        app.kubernetes.io/component: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: {{ .Values.nodeExporter.image }}
          ports:
            - containerPort: 9100