apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring-verkstedt.fullname" . }}-prometheus-svc
  labels:
    {{- include "monitoring-verkstedt.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "monitoring-verkstedt.name" . }}
    app.kubernetes.io/component: prometheus
  ports:
    - name: web
      port: 9090
      targetPort: 9090