{{- if .Values.db.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secret.name }}
  labels:
    {{- include "nginx-verkstedt.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.user | quote }}
  POSTGRES_DB: {{ .Values.db.name | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
{{- end }}
