prometheus:
  # Prometheus container image
  image: prom/prometheus:latest
  storage:
    # Size of the persistent volume for Prometheus data
    size: 2Gi

nodeExporter:
  # Node Exporter container image
  image: prom/node-exporter:latest
  # Name of the Node Exporter service (used in Prometheus targets)
  serviceName: node-exporter

# Content of prometheus.yml configuration file, passed via ConfigMap
conf:
  prometheus: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['{{ .Values.nodeExporter.serviceName }}:9100']